- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "woocommerce"
  color: "96588a"
  description: "Related to WooCommerce functionality"
- name: "printify"
  color: "7057ff"
  description: "Related to Printify integration"