name: Create Labels

on: [push]

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Labels
      uses: actions/github-script@v4
      with:
        script: |
          const labels = [
            { name: "bug", color: "d73a4a" },
            { name: "documentation", color: "0075ca" },
            { name: "duplicate", color: "cfd3d7" },
            { name: "enhancement", color: "a2eeef" },
            { name: "good first issue", color: "7057ff" },
            { name: "help wanted", color: "008672" },
            { name: "invalid", color: "e4e669" },
            { name: "question", color: "d876e3" },
            { name: "wontfix", color: "ffffff" },
          ];
          for (const label of labels) {
            try {
              await github.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                color: label.color,
              });
            } catch (error) {
              if (error.status === 422) {
                console.log(`Label "${label.name}" already exists`);
              } else {
                throw error;
              }
            }
          }