services:
  wordpress:
    build: .
    image: wordpress:php8.2-fpm
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - /var/cache/nginx:/var/cache/nginx
    depends_on:
      - wordpress

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress:
  mysql_data:
