services:
  wp_app:
    image: litespeedtech/openlitespeed
    container_name: wp_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8088:8088"  # WordPress site
      - "7080:7080"  # OpenLiteSpeed Admin Panel
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_HOME}
    volumes:
      - ./wp-content:/var/www/vhosts/localhost/html/wp-content/  # Install WordPress inside OpenLiteSpeed web root
      - ./vendor:/var/www/vhosts/localhost/html/vendor  # Ensure autoloading works
    depends_on:
      - wp_db
      - wp_redis
    networks:
      - wp_network

  wp_db:
    image: mariadb:latest
    container_name: wp_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  wp_redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - wp_network

networks:
  wp_network:

volumes:
  db_data:
