services:
  wordpress:
    context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: wordpress_printify
    restart: unless-stopped
    volumes:
      - ./wp-content/plugins/wp-woocommerce-printify-sync:/var/www/html/wp-content/plugins/wp-woocommerce-printify-sync
      - ./vendor:/var/www/html/vendor
      - wordpress_data:/var/www/html
      - php_logs:/var/log/php
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WP_DEBUG=${WP_DEBUG}
      - WP_DEBUG_LOG=${WP_DEBUG_LOG}
      - WP_DEBUG_DISPLAY=${WP_DEBUG_DISPLAY}
      - WP_ENVIRONMENT_TYPE=${WP_ENVIRONMENT_TYPE}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wordpress_net
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_printify
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9003:9003"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - wordpress_net
    depends_on:
      - wordpress

  db:
    image: mysql:8.0
    container_name: mysql_printify
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - wordpress_net

volumes:
  wordpress_data:
    name: wordpress_printify_data
  db_data:
    name: mysql_printify_data
  php_logs:
    name: php_printify_logs

networks:
  wordpress_net:
    name: wordpress_printify_network
    driver: bridge

# Configuration timestamp: 2025-02-23 19:58:28 UTC
# Updated by: ApolloWeb