version: '3.8'

services:
  app:
    image: ${APP_IMAGE_NAME}
    container_name: ${APP_CONTAINER_NAME}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html           # Persist WordPress core files
      - ./wp-content:/var/www/html/wp-content  # Persist wp-content (plugins, uploads, themes)
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini  # Custom PHP configuration
    environment:
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/nginx/certs  # Contains your SSL certificates
    depends_on:
      - app
    networks:
      - wordpress_network

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - wordpress_network

volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:
    driver: bridge