
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: nginx:alpine
    container_name: wordpress_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html/wp-content
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - wordpress_network

  php:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: wordpress_php
    volumes:
      - ./wp-content/plugins/:/var/www/plugins
      - ./phpcs.xml.dist:/var/www/html/phpcs.xml.dist:ro
      - ./.php-cs-fixer.php:/var/www/html/.php-cs-fixer.php:ro
      - ./phpstan.neon:/var/www/html/phpstan.neon:ro
      - ./eslint.config.js:/var/www/html/eslint.config.js:ro
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist:ro
      - ./tests/bootstrap.php:/var/www/html/tests/bootstrap.php:ro
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge
