version: '3.8'

services:
  web:
    image: robowen1972/wp_app
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./logs/:/var/log
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    image: robowen1972/wp_app
    container_name: php
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "33060:3306"
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
