services:
  nginx-php:
    container_name: nginx-php
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - app_data:/var/www/html
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./index.php:/var/www/html/index.php
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    environment:
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_PASSWORD=${WP_DB_PASSWORD}
      - WP_REDIS_HOST=${WP_REDIS_HOST}
      - WP_REDIS_PASSWORD=${WP_REDIS_PASSWORD}
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - WP_CONTENT_DIR=${WP_CONTENT_DIR}
      - WP_CONTENT_URL=${WP_CONTENT_URL}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WP_DEBUG=${WP_DEBUG}
      - WP_DEBUG_LOG=${WP_DEBUG_LOG}
      - WP_DEBUG_DISPLAY=${WP_DEBUG_DISPLAY}
      - SCRIPT_DEBUG=${SCRIPT_DEBUG}
      - WP_MEMORY_LIMIT=${WP_MEMORY_LIMIT}
      - WP_MAX_MEMORY_LIMIT=${WP_MAX_MEMORY_LIMIT}
      - DISABLE_WP_CRON=${DISABLE_WP_CRON}
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
      - DISALLOW_FILE_EDIT=${DISALLOW_FILE_EDIT}
      - DISALLOW_FILE_MODS=${DISALLOW_FILE_MODS}
      - FILESYSTEM_METHOD=${FILESYSTEM_METHOD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_AUTH=${SMTP_AUTH}

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MAXMEMORY=${REDIS_MAXMEMORY}
      - REDIS_POLICY=${REDIS_POLICY}

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  app_data:
    driver: local
