services:
  nginx-php:
    container_name: nginx-php
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - app_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./etc/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./index.php:/var/www/html/index.php
      - ./.env:/var/www/html/.env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    environment:
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - WORDPRESS_DATABASE_HOST=${WP_DB_HOST}
      - WORDPRESS_DATABASE_USER=${WP_DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${WP_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WORDPRESS_BLOG_NAME=${WP_BLOG_NAME}
      - WORDPRESS_LOCALE=${WP_LOCALE}
      - WP_ENABLE_REDIS_CACHE=${WP_ENABLE_REDIS_CACHE}
      - WP_CACHE=${WP_CACHE}
      - WP_REDIS_CLIENT=${WP_REDIS_CLIENT}
      - WP_REDIS_DATABASE=${WP_REDIS_DATABASE}
      - WP_REDIS_TIMEOUT=${WP_REDIS_TIMEOUT}
      - WP_REDIS_READ_TIMEOUT=${WP_REDIS_READ_TIMEOUT}
      - WP_REDIS_EXPIRE=${WP_REDIS_EXPIRE}
      - WP_REDIS_MAXTTL=${WP_REDIS_MAXTTL}
      - WP_DEBUG=${WP_DEBUG}
      - WP_DEBUG_LOG=${WP_DEBUG_LOG}
      - WP_DEBUG_DISPLAY=${WP_DEBUG_DISPLAY}
      - SCRIPT_DEBUG=${SCRIPT_DEBUG}
      - WP_MEMORY_LIMIT=${WP_MEMORY_LIMIT}
      - WP_MAX_MEMORY_LIMIT=${WP_MAX_MEMORY_LIMIT}
      - DISABLE_WP_CRON=${DISABLE_WP_CRON}
      - FILESYSTEM_METHOD=${FILESYSTEM_METHOD}
      - DISALLOW_FILE_EDIT=${DISALLOW_FILE_EDIT}
      - DISALLOW_FILE_MODS=${DISALLOW_FILE_MODS}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_FIRSTNAME=${WP_ADMIN_FIRSTNAME}
      - WP_ADMIN_LASTNAME=${WP_ADMIN_LASTNAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_AUTH=${SMTP_AUTH}
      - WP_CONTENT_DIR=${WP_CONTENT_DIR}
      - WP_CONTENT_URL=${WP_CONTENT_URL}
      - WPLANG=${WPLANG}

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    networks:
        - app_network
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${WP_DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    depends_on:
      - nginx-php
    env_file:
      - .env
    command: ["ngrok", "http", "--domain=${NGROK_DOMAIN}", "nginx-php:80"]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  php_fpm_data:
    driver: local
  app_data:
    driver: local
