services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_apache
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./docker/apache/httpd.conf:/etc/apache2/httpd.conf:ro
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge