services:
  - name: mariadb
    type: web  # Render does not support private services, using web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: starter
    image: mariadb:latest  # Use official MariaDB image
    envVars:
      - key: WP_DB_HOST
        value: mariadb.internal
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
      - key: MARIADB_ROOT_PASSWORD  # ✅ REQUIRED FIX
        sync: false
      - key: MYSQL_MAX_CONNECTIONS
        value: "200"
      - key: MYSQL_KEY_BUFFER_SIZE
        value: "32M"
      - key: MYSQL_QUERY_CACHE_SIZE
        value: "16M"
      - key: MYSQL_TABLE_OPEN_CACHE
        value: "2000"
      - key: MYSQL_SORT_BUFFER_SIZE
        value: "2M"
    autoDeploy: false
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 10  # Persistent database storage
