services:
  - name: wordpress
    type: web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./Dockerfile.prod
    envVars:
      - key: WP_DB_HOST
        value: false
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
    autoDeploy: true

  - name: mariadb
    type: service  # Fix: Changed from privateService to service
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./mariadb/Dockerfile
    envVars:
      - key: WP_DB_HOST
        value: false
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
      - key: WP_DB_ROOT_PASSWORD
        sync: false
    autoDeploy: false
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 10  # Persistent database storage

  - name: redis
    type: service  # Fix: Changed from privateService to service
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./redis/Dockerfile
    envVars:
      - key: REDIS_HOST
        value: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_MAXMEMORY
        value: false
      - key: REDIS_POLICY
        value: false
    autoDeploy: false
