services:
  - name: wordpress
    type: web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: starter
    dockerfilePath: ./Dockerfile.prod
    envVars:
      - key: WP_DB_HOST
        value: mariadb.internal
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
    autoDeploy: true

  - name: mariadb
    type: web  # Render does not support private services, using web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: starter
    dockerfilePath: ./mariadb/Dockerfile
    envVars:
      - key: WP_DB_HOST
        value: mariadb.internal
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
      - key: WP_DB_ROOT_PASSWORD
        sync: false
      - key: MYSQL_MAX_CONNECTIONS
        value: "200"
      - key: MYSQL_KEY_BUFFER_SIZE
        value: "32M"
      - key: MYSQL_QUERY_CACHE_SIZE
        value: "16M"
      - key: MYSQL_TABLE_OPEN_CACHE
        value: "2000"
      - key: MYSQL_SORT_BUFFER_SIZE
        value: "2M"
    autoDeploy: false  # Keep it internal
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 10  # Persistent database storage

  - name: redis
    type: web  # Render does not support private services, using web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: starter
    dockerfilePath: ./redis/Dockerfile
    envVars:
      - key: REDIS_HOST
        value: redis.internal
      - key: REDIS_MAXMEMORY
        value: "256mb"
      - key: REDIS_POLICY
        value: "allkeys-lru"
    autoDeploy: false  # Keep it internal
