services:
  - name: wordpress
    type: web
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./Dockerfile.prod   # Path to WordPress Dockerfile
    envVars:
      - key: WP_DB_HOST
        value: false
      - key: WP_DB_NAME
        sync: false
      - key: WP_DB_USER
        sync: false
      - key: WP_DB_PASSWORD
        sync: false
      - key: WP_REDIS_HOST
        value: false
      - key: WP_REDIS_PASSWORD
        sync: false
    autoDeploy: true

  - name: mariadb
    type: privateService
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./mariadb/Dockerfile   # Path to MariaDB Dockerfile
    envVars:
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
    autoDeploy: false

  - name: redis
    type: privateService
    env: docker
    repo: https://github.com/ApolloWeb/wp-woocommerce-printify-sync
    plan: free
    dockerfilePath: ./redis/Dockerfile   # Path to Redis Dockerfile
    envVars:
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_MAXMEMORY
        value: false
      - key: REDIS_POLICY
        value: allkeys-lru
    autoDeploy: false
