name: Docker Build Cloud CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: cloud

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build & Push Docker Image
        run: |
          docker buildx build --builder cloud-robowen1972-cloud-builder \
                              --platform=linux/amd64 \
                              --cache-from=type=gha \
                              --cache-to=type=gha,mode=max \
                              --tag=robowen1972/wordpress_app \
                              --push .
