name: Code Quality Check

on:
  push:
    branches:
      - mercury
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer, phpstan, php-cs-fixer, phpcs, phpcbf, phplint
        extensions: mbstring, dom

    - name: Install Composer dependencies
      run: |
        composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        composer --file=./.github/workflows/composer.json install --prefer-dist --no-progress
        vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install ESLint
      run: npm install -g eslint

    # ✅ 1️⃣ Run PHP Lint (Syntax Check)
    - name: Run PHP Lint (Syntax Check)
      run: |
        find . \( -path ./vendor -o -path ./node_modules -o -path ./.github \) -prune -o -name "*.php" -print | xargs -n1 php -l
      continue-on-error: false

    # ✅ 2️⃣ Run PHP CodeSniffer (PHPCS) with WordPress Standards
    - name: Run PHP CodeSniffer (PHPCS)
      run: |
        vendor/bin/phpcs --standard=.github/workflows/phpcs.xml.dist
      continue-on-error: true

    # ✅ 3️⃣ Run PHP Code Beautifier (PHPCBF) to auto-fix PHPCS issues
    - name: Run PHP Code Beautifier (PHPCBF)
      run: |
        vendor/bin/phpcbf --standard=.github/workflows/phpcs.xml.dist
      continue-on-error: true

    # ✅ 4️⃣ Run PHP-CS-Fixer for additional formatting fixes
    - name: Run PHP-CS-Fixer (PHP Formatting)
      run: |
        vendor/bin/php-cs-fixer fix --config=.github/workflows/.php-cs-fixer.php --dry-run --verbose
      continue-on-error: true

    # ✅ 5️⃣ Run PHPStan (Static Analysis)
    - name: Run PHPStan (Static Analysis)
      run: |
        vendor/bin/phpstan analyse --configuration=.github/workflows/phpstan.neon
      continue-on-error: true

    # ✅ 6️⃣ Run ESLint on all JavaScript and TypeScript files
    - name: Run ESLint (JavaScript Syntax Check)
      run: |
        npx eslint --config .github/workflows/eslint.config.js . --fix
      continue-on-error: true
