name: Code Quality Check

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch
      - 'feature/*'  # Optionally, include feature branches
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to the master branch

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom

    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction

    - name: Install Node.js and ESLint
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the required Node.js version
    - name: Install ESLint
      run: |
        npm install -g eslint

    - name: Install PHPStan
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar require --dev phpstan/phpstan

    - name: Run PHP-CS-Fixer (PHP formatting)
      run: |
        vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --verbose
      continue-on-error: true  # Allows workflow to continue even with issues

    - name: Run PHPStan (Static analysis)
      run: |
        vendor/bin/phpstan analyse src/  # Adjust the directory to match your codebase
      continue-on-error: true  # Allows workflow to continue even with issues

    - name: Run ESLint (JavaScript syntax check)
      run: |
        eslint src/ --ext .js --fix  # Adjust the directory to match your JS files
      continue-on-error: true  # Allows workflow to continue even with issues
