name: Code Quality Check

on:
  push:
    branches:
      - mercury
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up PHP 8.1
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer, phpstan, php-cs-fixer, phpcs, phpcbf, phplint
        extensions: mbstring, dom

    # ✅ Generate `composer.json` inside GitHub Actions
    - name: Generate composer.json
      run: |
        cat <<EOL > composer.json
        {
          "name": "myvendor/wp-woocommerce-printify-sync",
          "description": "WooCommerce Printify Sync Plugin",
          "type": "project",
          "require": {
            "php": ">=8.1"
          },
          "require-dev": {
            "friendsofphp/php-cs-fixer": "^3.0",
            "squizlabs/php_codesniffer": "^3.7",
            "wp-coding-standards/wpcs": "^3.0",
            "phpstan/phpstan": "^1.10",
            "dealerdirect/phpcodesniffer-composer-installer": "^1.0"
          }
        }
        EOL
        cat composer.json  # Show the created file

    # ✅ Install Composer Dependencies
    - name: Install Composer dependencies
      run: |
        composer install --prefer-dist --no-progress
        vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install ESLint
      run: npm install -g eslint

    # ✅ 1️⃣ Run PHP Lint (Syntax Check)
    - name: Run PHP Lint (Syntax Check)
      run: find . -name "*.php" | xargs -n1 php -l
      continue-on-error: false

    # ✅ 2️⃣ Run PHP CodeSniffer (PHPCS) with WordPress Standards
    - name: Run PHP CodeSniffer (PHPCS)
      run: vendor/bin/phpcs --standard=WordPress-Core --extensions=php .
      continue-on-error: true

    # ✅ 3️⃣ Run PHP Code Beautifier (PHPCBF) to auto-fix PHPCS issues
    - name: Run PHP Code Beautifier (PHPCBF)
      run: vendor/bin/phpcbf --standard=WordPress-Core --extensions=php .
      continue-on-error: true

    # ✅ 4️⃣ Run PHP-CS-Fixer for additional formatting fixes
    - name: Run PHP-CS-Fixer (PHP Formatting)
      run: vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --verbose .
      continue-on-error: true

    # ✅ 5️⃣ Run PHPStan (Static Analysis)
    - name: Run PHPStan (Static Analysis)
      run: vendor/bin/phpstan analyse --level=max .
      continue-on-error: true

    # ✅ 6️⃣ Run ESLint on all JavaScript and TypeScript files
    - name: Run ESLint (JavaScript Syntax Check)
      run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix
      continue-on-error: true
