name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
      - main
  pull_request:
    branches:
      - gemini
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secrets Availability
        id: check_secrets
        run: |
          echo "Checking for Docker Hub credentials..."
          if [[ -n "${{ secrets.DOCKER_USER }}" && -n "${{ secrets.DOCKER_PAT }}" ]]; then
            echo "Both DOCKER_USER and DOCKER_PAT secrets are available"
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "One or both secrets are missing"
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          fi
          # This will be masked in logs if the secret exists
          echo "DOCKER_USER length: ${#DOCKER_USER}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_login
        if: success()  # Try login regardless of secrets check
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        continue-on-error: true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ steps.docker_login.outcome == 'success' }}
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}

      - name: Image Status
        shell: /usr/bin/bash -e {0}
        run: |
          if [[ "${{ steps.check_secrets.outputs.has_secrets }}" == "true" ]]; then
            echo "✅ Docker image has been pushed to Docker Hub"
            echo "You can now pull it with: docker pull robowen1972/wp-woocommerce-printify-sync:latest"
          else
            echo "⚠️ Docker image was built but NOT pushed to Docker Hub due to missing credentials"
            echo "Please check that DOCKER_USER and DOCKER_PAT secrets in your GitHub repository settings are correct"
