name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
  pull_request:
    branches:
      - gemini
    types: [opened, synchronize, reopened]
    secrets: inherit  # Allow secrets in PRs from forks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Debugging step: Check if secrets are available
      - name: Debug Secrets (Check if they exist)
        run: |
          if [[ -z "${{ secrets.DOCKER_USER }}" ]]; then
            echo "❌ DOCKER_USER secret is missing!"
            exit 1
          else
            echo "✅ DOCKER_USER is set"
          fi

          if [[ -z "${{ secrets.DOCKER_PAT }}" ]]; then
            echo "❌ DOCKER_PAT secret is missing!"
            exit 1
          else
            echo "✅ DOCKER_PAT is set"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}

      - name: Post-Build Debugging
        run: |
          echo "✅ Build completed successfully!"
