name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
      - main  # Added main branch to ensure workflow runs on common branch names
  pull_request:
    branches:
      - gemini
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Docker Hub Secrets
        id: check_secrets
        run: |
          if [[ -z "${{ secrets.DOCKER_USER }}" || -z "${{ secrets.DOCKER_PAT }}" ]]; then
            echo "Docker Hub credentials are missing. Image will be built but not pushed."
            echo "has_secrets=false" >> $GITHUB_OUTPUT
          else
            echo "Docker Hub credentials found. Image will be built and pushed."
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ steps.check_secrets.outputs.has_secrets == 'true' }}
          tags: |
            apolloweb/wp-woocommerce-printify-sync:latest
            apolloweb/wp-woocommerce-printify-sync:${{ github.sha }}

      - name: Image Status
        run: |
          if [[ "${{ steps.check_secrets.outputs.has_secrets }}" == "true" ]]; then
            echo "✅ Docker image has been pushed to Docker Hub"
            echo "You can now pull it with: docker pull robowen1972/wp-woocommerce-printify-sync:latest"
          else
            echo "⚠️ Docker image was built but NOT pushed to Docker Hub due to missing credentials"
            echo "Please check that DOCKER_USER and DOCKER_PAT secrets in your GitHub repository settings are correct"
