name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
      - main
  pull_request:
    branches:
      - gemini
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3  # Updated to v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        # This won't fail the workflow if login fails
        continue-on-error: true
        id: login

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5  # Updated to v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ steps.login.outcome == 'success' }}
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}
      
      - name: Build Status
        run: |
          if [ "${{ steps.login.outcome }}" == "success" ]; then
            echo "✅ Image successfully built and pushed to Docker Hub"
            echo "You can pull it with: docker pull robowen1972/wp-woocommerce-printify-sync:latest"
          else
            echo "⚠️ Image was built but NOT pushed to Docker Hub due to login issues"
            echo "Please verify your Docker Hub credentials"
          fi
