name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
  pull_request:
    branches:
      - gemini

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This will skip certain steps in PR from forks due to security
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Check if PR from fork
        id: check_fork
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
            echo "⚠️ This is a PR from a fork. For security, secrets won't be available and we'll skip pushing to Docker Hub."
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        if: steps.check_fork.outputs.is_fork != 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ steps.check_fork.outputs.is_fork != 'true' }}
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}

      - name: Post-Build Debugging
        run: echo "✅ Build completed successfully!"