name: Build and Push Docker Image v2

on:
  push:
    branches:
      - gemini
  pull_request:
    branches:
      - gemini

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Debugging Information
      - name: Debug Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "This is a pull request"
            echo "PR from fork: ${{ github.event.pull_request.head.repo.fork }}"
          fi
      
      # Determine if we should push
      - name: Process Based on Event Type
        id: process_type
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
            echo "Running PR from fork - will build but not push"
            echo "should_push=false" >> $GITHUB_ENV
          else
            echo "Running push or internal PR - will attempt to push"
            echo "should_push=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Debug Secrets
      - name: Debug Secrets
        run: |
          if [[ -z "${{ secrets.DOCKER_USER }}" || -z "${{ secrets.DOCKER_PAT }}" ]]; then
            echo "❌ ERROR: DOCKER_USER or DOCKER_PAT is not set!"
            exit 1
          else
            echo "✅ Secrets are set."
          fi

      # Clear Docker Cache
      - name: Clear Docker Cache
        run: |
          docker builder prune -af
          docker system prune -af --volumes

      # Login to Docker Hub
      - name: Login to Docker Hub
        if: env.should_push == 'true'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ env.should_push == 'true' }}
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}

      # Logout from Docker Hub
      - name: Logout from Docker Hub
        if: env.should_push == 'true'
        run: docker logout

      # Post-Build Debugging
      - name: Post-Build Debugging
        run: echo "✅ Build completed successfully!"
