name: Docker Build and Publish

on:
  push:
    branches: [ gemini ]
  pull_request:
    branches: [ gemini ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Debug Information
        run: echo "Running on ${{ github.ref }} - Event: ${{ github.event_name }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io  # Explicitly set registry
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          # No other parameters that could cause conflicts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}
