name: Build and Push Docker Image

on:
  push:
    branches:
      - gemini
  pull_request:
    branches:
      - gemini

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"

      - name: Debug Secrets (Check if they exist)
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: |
          if [ -z "$DOCKER_USER" ]; then
            echo "❌ DOCKER_USER secret is missing!"
            echo "Please add this secret in your GitHub repository settings."
            exit 1
          else
            echo "✅ DOCKER_USER is set"
          fi

          if [ -z "$DOCKER_PAT" ]; then
            echo "❌ DOCKER_PAT secret is missing!"
            echo "Please add this secret in your GitHub repository settings."
            exit 1
          else
            echo "✅ DOCKER_PAT is set"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            robowen1972/wp-woocommerce-printify-sync:latest
            robowen1972/wp-woocommerce-printify-sync:${{ github.sha }}

      - name: Post-Build Debugging
        run: echo "✅ Build completed successfully!"