name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: 
      - created

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM dependencies
        run: npm install

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Run PHP Lint
        run: ./vendor/bin/parallel-lint --exclude .git --exclude vendor .

      - name: Run PHPCS
        run: composer run phpcs

      - name: Run PHPCBF
        run: composer run phpcbf

      - name: Run PHPStan
        run: composer run phpstan

      - name: Run PHP-CS-Fixer
        run: composer run php-cs-fixer

      - name: Run ESLint
        run: npm run lint

      - name: Upload analysis results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-analysis-${{ matrix.php }}
          path: |
            ./phpcs.xml
            ./phpstan-report.json
            ./eslint-report.json
          retention-days: 7