name: PHPUnit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: WordPress ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: ['8.2']
        wordpress: ['latest', '6.4', '6.3']
        include:
          - php: '8.2'
            wordpress: '6.0'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install WooCommerce
        run: |
          composer require woocommerce/woocommerce-sniffs --dev
          composer require woocommerce/woocommerce-testing --dev

      - name: Install WordPress Test Suite
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress }}

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress
          
      - name: Run Tests
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: build/logs/clover.xml
          fail_ci_if_error: true

  lint:
    name: PHP Code Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2, cs2pr

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCS check
        run: vendor/bin/phpcs --standard=WordPress --report=checkstyle | cs2pr

      - name: PHPStan analysis
        run: vendor/bin/phpstan analyse --error-format=github