name: Update README with Copilot

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:  # Also runs on PRs
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          persist-credentials: true

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run update-readme script
        run: node update-readme.js

      - name: Show Git status
        run: git status

      - name: Stage README changes
        run: git add README.md

      - name: Commit changes if any
        run: |
          git commit -a -m "chore: update README with Copilot-generated descriptions" || echo "No changes to commit"

      - name: Push changes
        run: |
          branch=${GITHUB_REF#refs/heads/}
          echo "Pushing to branch: $branch"
          git push origin HEAD:$branch
